routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::get('/posts/create', 'PostsController@create')->name('posts.create');
    Route::post('/posts', 'PostsController@store')->name('posts.store');
    Route::get('/posts/manager', 'PostsController@manager')->name('posts.manager');
    Route::get('/posts/{id}/edit', 'PostsController@edit')->name('posts.edit');
    Route::put('/posts/{id}', 'PostsController@update')->name('posts.update');
    Route::delete('/posts/{id}', 'PostsController@destroy')->name('posts.destroy');

    Route::middleware(['is_admin'])->group(function () {
        Route::get('/review', 'PostsController@review')->name('posts.review');
        Route::put('posts/{id}/publish-at', 'PostsController@publishAt')->name('posts.publishAt');
        Route::put('posts/{id}/publish', 'PostsController@publish')->name('posts.publish');
        Route::put('posts/{id}/unpublish', 'PostsController@unpublish')->name('posts.unpublish');
    });
});

Route::get('/posts/{slug}', 'PostsController@show')->name('posts.show');

app/Post.php
<?php

namespace App;

use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use Sluggable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'slug', 'user_id', 'content', 'published_at',
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at', 'published_at'];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title',
            ]
        ];
    }

    /**
     * Get the user that owns the post.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Scope a query to only include published posts.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param $includeWillPublish
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePublished($query, $includeWillPublish = false)
    {
        return $query->whereNotNull('published_at')
            ->where(function ($q) use ($includeWillPublish) {
                if (! $includeWillPublish) {
                    $q->where('published_at', '<=', now()->toDateTimeString());
                }
            });
    }

    /**
     * Scope a query to only include unpublished posts.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeUnpublished($query)
    {
        return $query->whereNull('published_at');
    }

    /**
     * Find a post by its primary slug or throw an exception.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $slug
     *
     * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection
     *
     * @throws \Illuminate\Database\Eloquent\ModelNotFoundException
     */
    public function scopeFindBySlugOrFail($query, $slug)
    {
        return $query->whereSlug($slug)->firstOrFail();
    }

    /**
     * Get the post's detail url.
     *
     * @return string
     */
    public function getDetailUrlAttribute()
    {
        return route('posts.show', $this->slug);
    }

    /*
     * Check post is published or not.
     */
    public function isPublished()
    {
        return $this->published_at;
    }

    /*
     * Publish the post.
     */
    public function publish($datetime = '')
    {
        $this->update([
            'published_at' => $datetime
                ? Carbon::createFromFormat('m/d/Y h:i A', $datetime) : now(),
        ]);
    }

    /**
     * Unpublish the post.
     */
    public function unpublish()
    {
        $this->update([
            'published_at' => null,
        ]);
    }

    /**
     * Scope a query to filter posts.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param Request $request
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeFilter($query, Request $request)
    {
        if ($request->filled('datetime')) {
            $dates = explode(' - ', $request->get('datetime'));

            $query->whereDate('created_at', '>=', Carbon::createFromFormat('m/d/Y', $dates[0])->toDateString());

            $query->whereDate('created_at', '<=', Carbon::createFromFormat('m/d/Y', $dates[1])->toDateString());
        }

        if ($request->filled('status')) {
            if ($request->get('status') == 'publish') {
                $query->published(true);
            } else {
                $query->unpublished();
            }
        }

        if ($request->filled('sort')) {
            if ($request->get('sort') == 'newest') {
                $query->orderBy('created_at', 'desc');
            } else {
                $query->orderBy('created_at', 'asc');
            }

        } else {
            $query->latest('created_at');
        }

        return $query;
    }

    /**
     * Scope a query to sort posts by published_at.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param $column
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeLatest($query, $column = 'published_at')
    {
        return $query->orderBy($column, 'desc');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostsController extends Controller
{
    public function show($slug)
    {
        $post = Post::with('user')->findBySlugOrFail($slug);

        return view('posts.show', compact('post'));
    }

    public function create()
    {
        return view('posts.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'content' => 'required',
        ]);

        $user = auth()->user();

        $user->posts()->create($request->all());

        flash('Created blog successfully.')->success();

        return redirect()->route('posts.manager');
    }

    public function manager(Request $request)
    {
        $user= auth()->user();

        $posts = $user->posts()->latest('created_at')->paginate(5);

        return view('posts.manager', compact('posts'));
    }

    public function edit($id)
    {
        $post = auth()->user()->posts()->findOrFail($id);

        return view('posts.edit', compact('post'));
    }

    public function update($id, Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'content' => 'required',
        ]);

        $post = auth()->user()->posts()->findOrFail($id);

        $post->update($request->all());

        flash('Blog updated successfully.')->success();

        return redirect()->route('posts.edit', $id);
    }

    public function destroy($id)
    {
        $post = auth()->user()->posts()->findOrFail($id);

        $post->delete();

        flash('Blog deleted successfully.')->success();

        return response()->json([]);
    }

    public function review(Request $request)
    {
        $posts = Post::with('user')
            ->filter($request)
            ->paginate(5);

        return view('posts.review', compact('posts'));
    }

    public function publishAt($id, Request $request)
    {
        $this->validate($request, [
            'datetime' => 'required|date_format:"m/d/Y h:i A"',
        ]);

        $post = Post::findOrFail($id);

        $post->publish($request->datetime);

        flash('Blog was set schedule publish time.')->success();

        return response()->json([]);
    }

    public function publish($id)
    {
        $post = Post::findOrFail($id);

        $post->publish();

        flash('Blog was published successfully.')->success();

        return response()->json([]);
    }

    public function unpublish($id)
    {
        $post = Post::findOrFail($id);

        $post->unpublish();

        flash('Blog was unpublished.')->success();

        return response()->json([]);
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('title', 'Create post')

@push('styles')
    <link href="{{ asset('plugins/simplemde/simplemde.min.css') }}" rel="stylesheet">
@endpush

@push('scripts')
    <script src="{{ asset('plugins/simplemde/simplemde.min.js') }}"></script>

    <script>
        var simplemde = new SimpleMDE();
    </script>
@endpush

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2>Create blog</h2>
                <form id="contact-form" method="post" action="{{ route('posts.store') }}" role="form" novalidate>
                    @csrf

                    @include('partials.errors')

                    <div class="controls">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="title">Title *</label>
                                    <input id="title" type="text" name="title" class="form-control" placeholder="Please enter the title *" required="required" data-error="Title is required." value="{{ old('title') }}">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="content">Content *</label>
                                <textarea id="content" name="content" class="form-control" placeholder="" rows="4" required="required" data-error="Content" value="{{ old('content') }}"></textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <input type="submit" class="btn btn-primary btn-send" value="Save blog">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-muted"><strong>*</strong> These fields are required.</p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit post')

@push('styles')
    <link href="{{ asset('plugins/simplemde/simplemde.min.css') }}" rel="stylesheet">
@endpush

@push('scripts')
    <script src="{{ asset('plugins/simplemde/simplemde.min.js') }}"></script>

    <script>
        var simplemde = new SimpleMDE();
    </script>
@endpush

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2>Edit blog</h2>
                <form id="contact-form" method="post" action="{{ route('posts.update', $post->id) }}" role="form" novalidate>
                    @csrf
                    @method('PUT')

                    @include('partials.errors')

                    <div class="controls">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="title">Title *</label>
                                    <input id="title" type="text" name="title" class="form-control" placeholder="Please enter the title *" required="required" data-error="Title is required." value="{{ old('title', $post->title) }}">
                                    <div class="help-block with-errors"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="content">Content *</label>
                                <textarea id="content" name="content" class="form-control" placeholder="" rows="4" required="required" data-error="Content">{{ old('content', $post->content) }}</textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <input type="submit" class="btn btn-primary btn-send" value="Save blog">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-muted"><strong>*</strong> These fields are required.</p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/manager.blade.php
@extends('layouts.app')

@section('title', 'Manager')

@push('scripts')
    <script>
        $(document).ready(function() {
            $('.btn-delete').on('click', function (e) {
                e.preventDefault();

                var url = $(this).data('url');

                swal({
                    title: "Are you sure?",
                    text: "",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    closeOnConfirm: true
                }).then(function () {
                    $.ajax({
                        url : url,
                        type : 'DELETE',
                        beforeSend: function (xhr) {
                            var token = $('meta[name="csrf-token"]').attr('content');
                            if (token) {
                                return xhr.setRequestHeader('X-CSRF-TOKEN', token);
                            }
                        }
                    }).always(function (data) {
                        window.location.reload();
                    });
                });
            });
        });
    </script>
@endpush

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="my-4">Manager my blog
                </h1>

                @foreach ($posts as $post)
                    <div class="card mb-4 @if (! $post->isPublished()) bg-light @endif">
                        <div class="card-header">
                            <h5>{{ $post->title }}

                            @if ($post->isPublished())
                            <span class="badge badge-primary float-right">Published</span></h5>
                            @else
                                <span class="badge badge-secondary float-right">Unpublished</span></h5>
                            @endif

                        </div>
                        <div class="card-body ">
                            {{--<h5 class="card-title"></h5>--}}
                            <p class="card-text">@markdown($post->content)</p>
                            {{--<a href="{{ $post->detail_url }}" class="btn btn-primary">Read more ...</a>--}}
                        </div>
                        <div class="card-footer text-muted">
                            @if ($post->isPublished())
                                Published at {{ $post->published_at->format('F d, Y h:i A') }}</span>
                            @else
                                Unpublished
                            @endif
                            <div class="float-right">
                            <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-info btn-sm">Edit</a>
                            <button class="btn btn-danger btn-sm btn-delete" data-url="{{ route('posts.destroy', $post->id) }}">Delete</button>
                            </div>
                        </div>
                    </div>
                @endforeach

                {{ $posts->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/posts/review.blade.php
@extends('layouts.app')

@section('title', 'Admin')

@push('styles')
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
@endpush

@push('scripts')
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script>

        $(document).ready(function() {
            function cb(start, end) {
                $('input[name="datetime"] span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
            }

            $('input[name="datetime"]').daterangepicker({
                autoUpdateInput: false,
                locale: {
                    cancelLabel: 'Clear'
                },
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                }
            }, cb);

            $('input[name="datetime"]').on('apply.daterangepicker', function(ev, picker) {
                $(this).val(picker.startDate.format('MM/DD/YYYY') + ' - ' + picker.endDate.format('MM/DD/YYYY'));
            });

            $('input[name="datetime"]').on('cancel.daterangepicker', function(ev, picker) {
                $(this).val('');
            });

            $('.btn-publish-at').on('click', function (e) {
                var url = $(this).data('url');

                swal({
                    title: "Pick datetime to publish this post..",
                    showCancelButton: true,
                    confirmButtonText: 'Update',
                    html:'<input id="datetimepicker" type="text" class="form-control" autofocus value="{{ now()->addDay()->setTime(9, 0)->format('m/d/Y h:i A') }}">',
                    onOpen: function() {
                        $('#datetimepicker').daterangepicker({
                            singleDatePicker: true,
                            timePicker: true,
                            showDropdowns: true,
                            locale: {
                                format: 'MM/DD/YYYY hh:mm A'
                            }
                        });
                    },
                    preConfirm: (datetime) => {

                    }
                }).then((result) => {
                    if (result.value) {
                        $.ajax({
                            url : url,
                            type : 'PUT',
                            data: {'datetime': $('#datetimepicker').val()},
                            beforeSend: function (xhr) {
                                var token = $('meta[name="csrf-token"]').attr('content');
                                if (token) {
                                    return xhr.setRequestHeader('X-CSRF-TOKEN', token);
                                }
                            }
                        }).done(function (data) {
                            window.location.reload();
                        }).fail(function () {
                            swal('', 'Error', 'error');
                        });
                    }
                });
            });

            $('.btn-publish').on('click', function (e) {
                e.preventDefault();

                var url = $(this).data('url');

                $.ajax({
                    url : url,
                    type : 'PUT',
                    beforeSend: function (xhr) {
                        var token = $('meta[name="csrf-token"]').attr('content');
                        if (token) {
                            return xhr.setRequestHeader('X-CSRF-TOKEN', token);
                        }
                    }
                }).always(function (data) {
                    window.location.reload();
                });
            });

            $('.btn-unpublish').on('click', function (e) {
                e.preventDefault();

                var url = $(this).data('url');

                swal({
                    title: "Are you sure?",
                    text: "",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    closeOnConfirm: true
                }).then((ok) => {
                    if (ok.value) {
                        $.ajax({
                            url : url,
                            type : 'PUT',
                            beforeSend: function (xhr) {
                                var token = $('meta[name="csrf-token"]').attr('content');
                                if (token) {
                                    return xhr.setRequestHeader('X-CSRF-TOKEN', token);
                                }
                            }
                        }).always(function (data) {
                            window.location.reload();
                        });
                    }
                });
            });
        });
    </script>
@endpush

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="my-4">All blog
                </h1>

                <form id="contact-form" method="get" role="form" novalidate>
                    <div class="controls">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="datetime" placeholder="Date" autocomplete="off" value="{{ request('datetime') }}">
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <select class="form-control" name="status">
                                        <option value=''>All status</option>
                                        @foreach (config('blog.filters.statuses') as $status => $name)
                                            @if (request('status') == $status)
                                                <option value="{{ $status }}" selected> {{ $name }} </option>
                                            @else
                                                <option value="{{ $status }}"> {{ $name }} </option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <div class="form-group">
                                    <select class="form-control" name="sort">
                                        <option value="">Sort by..</option>
                                        @foreach (config('blog.filters.sorts') as $key => $name)
                                            @if (request('sort') == $key)
                                                <option value="{{ $key }}" selected> {{ $name }} </option>
                                            @else
                                                <option value="{{ $key }}"> {{ $name }} </option>
                                            @endif
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-2 float-right">
                                <input type="submit" class="btn btn-primary btn-send" value="Filter post">
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </form>

                @foreach ($posts as $post)
                    <div class="card mb-4 @if (! $post->isPublished()) border-warning bg-light @endif">
                        <div class="card-header">
                            <h5>{{ $post->title }}

                                @if ($post->isPublished())
                                    <span class="badge badge-primary float-right">Published</span></h5>
                            @else
                                <span class="badge badge-secondary float-right">Unpublished</span></h5>
                            @endif

                        </div>
                        <div class="card-body ">
                            {{--<h5 class="card-title"></h5>--}}
                            <p class="card-text">@markdown($post->content)</p>
                            {{--<a href="{{ $post->detail_url }}" class="btn btn-primary">Read more ...</a>--}}
                        </div>
                        <div class="card-footer text-muted">
                            @if ($post->isPublished())
                                Published at {{ $post->published_at->format('F d, Y h:i A') }} by <span class="text-primary"> {{ $post->user->name }} </span></span>
                            @else
                                Unpublished
                            @endif
                            <div class="float-right">
                                @if ($post->isPublished())
                                <button class="btn btn-dark btn-sm btn-unpublish" data-url="{{ route('posts.unpublish', $post->id) }}">Unpublish this post</button>
                                @else
                                <button class="btn btn-primary btn-sm btn-publish" data-url="{{ route('posts.publish', $post->id) }}">Publish now</button>

                                <button class="btn btn-success btn-sm btn-publish-at" data-url="{{ route('posts.publishAt', $post->id) }}">Publish at...</button>
                                @endif
                            </div>
                        </div>
                    </div>
                @endforeach

                {{ $posts->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('title', $post->title)

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">

                <!-- Title -->
                <h1 class="mt-4">{{ $post->title }}</h1>

                <!-- Author -->
                <p class="lead">
                    by
                    <a href="#">{{ $post->user->name }}</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p>Posted on {{ $post->published_at->format('F d, Y') }} at {{ $post->published_at->format('h:i A') }}</p>

                <hr>

                <!-- Preview Image -->
                {{--<img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">--}}

                {{--<hr>--}}

                <!-- Post Content -->
                <p class="lead">
                    @markdown($post->content)
                </p>

                </div>

            </div>
        </div>
    </div>
@endsection